query CurrentExerciseLifecycle {
  currentExerciseLifecycle {
    id
    name
    status
    start
    end
    workspaceName
    workspaceDisplayName
    counts {
      events
      injects
      observations
      commands
      mediaPosts
      chatMessages
    }
  }
}
